services:
  game-app-server:
    build: ./game-app-server
    environment:
      - GAME_MODE=local
    depends_on:
      - fastapi-server

  fastapi-server:
    build: ./fastapi-server
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    expose:
      - "8000"